[package]
name = "statemint-integration-tests"
version = "1.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
description = "Statemint parachain runtime integration tests"

[dev-dependencies]
codec = { package = "parity-scale-codec", version = "3.4.0", default-features = false }

# Substrate
sp-runtime = { default-features = false, env = "${substrate}" }
frame-support = { default-features = false, env = "${substrate}" }
frame-system = { default-features = false, env = "${substrate}" }
sp-core = { default-features = false, env = "${substrate}" }
sp-weights = { default-features = false, env = "${substrate}" }
pallet-balances = { default-features = false, env = "${substrate}" }
pallet-assets = { default-features = false, env = "${substrate}" }

# Polakdot
polkadot-core-primitives = { default-features = false, env = "${polkadot}" }
polkadot-parachain = { default-features = false, env = "${polkadot}" }
polkadot-runtime-parachains = { env = "${polkadot}" }
polkadot-runtime = { env = "${polkadot}" }
xcm = { default-features = false, env = "${polkadot}" }
xcm-executor = { default-features = false, env = "${polkadot}" }
pallet-xcm = { default-features = false, env = "${polkadot}" }

# Cumulus
parachains-common = { default-features = false, env = "${cumulus}" }
penpal-runtime = { env = "${cumulus}" }
statemint-runtime = { env = "${cumulus}" }
statemine-runtime = { env = "${cumulus}" }

# Local
xcm-emulator = { default-features = false, env = "${xcm-emulator}" }
