[package]
name = "xcm-emulator-example"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"

[dependencies]
serde = { version = "1.0.137", optional = true }
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false }
proc-macro2 = "1.0.40"

# Substrate
frame-system = { env = "${substrate}" }
frame-support = { env = "${substrate}" }
pallet-balances = { env = "${substrate}" }
sp-runtime = { env = "${substrate}" }
sp-io = { env = "${substrate}" }

# Cumulius
cumulus-primitives-core = { env = "${cumulus}" }
cumulus-pallet-xcmp-queue = { env = "${cumulus}" }
parachain-info = { env = "${cumulus}" }

# Polkadot
xcm = { env = "${polkadot}" }
polkadot-primitives = { env = "${polkadot}" }
polkadot-parachain = { env = "${polkadot}" }
polkadot-runtime-parachains = { env = "${polkadot}" }
kusama-runtime = { env = "${polkadot}" }
pallet-xcm = { env = "${polkadot}" }

# Local
xcm-emulator = { path = ".." }
test-runtime = { path = "../test-runtime" }

[features]
runtime-benchmarks = [
    "kusama-runtime/runtime-benchmarks",
    "test-runtime/runtime-benchmarks",
]
