[package]
name = "xcm-emulator"
description = "Test kit to emulate cross-chain message passing and XCM execution"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0" }
paste = "1.0.5"
quote = "1.0.23"

# Substrate
frame-support = { env = "${substrate}" }
frame-system = { env = "${substrate}" }
sp-io = { env = "${substrate}" }
sp-std = { env = "${substrate}" }
sp-arithmetic = { env = "${substrate}" }

# Cumulus
cumulus-primitives-core = { env = "${cumulus}" }
cumulus-pallet-xcmp-queue = { env = "${cumulus}" }
cumulus-pallet-dmp-queue = { env = "${cumulus}" }
cumulus-pallet-parachain-system = { env = "${cumulus}" }
parachain-info = { env = "${cumulus}" }
cumulus-primitives-parachain-inherent = { env = "${cumulus}" }
cumulus-test-relay-sproof-builder = { env = "${cumulus}" }

# Polkadot
xcm = { env = "${polkadot}" }
xcm-executor = { env = "${polkadot}" }
polkadot-primitives = { env = "${polkadot}" }
polkadot-runtime-parachains = { env = "${polkadot}" }
